apiVersion: apps/v1
kind: Deployment
metadata:
  name: banias-frontend-deplyoment
  labels:
     app: banias-frontend
spec:
  replicas: 3
  selector:
    matchLabels:
        app: banias-frontend
  template:
      metadata:
        labels:
          app: banias-frontend

      spec:
        containers:
        - name: "banias-frontend"
          image: "gcr.io/aviv-playground/banias-frontend:test"
          volumeMounts:
          - name: google-cloud-key
            mountPath: /var/secrets/google
          ports:
          - containerPort: 8081
          env:
          - name: "BANIAS_PROJECTID"
            valueFrom:
              configMapKeyRef:
                key: "BANIAS_PROJECTID"
                name: "banias-frontend-config"
          - name: "BANIAS_DEBUG"
            valueFrom:
              configMapKeyRef:
                key: "BANIAS_DEBUG"
                name: "banias-frontend-config"
          - name: "BANIAS_TOPIC"
            valueFrom:
              configMapKeyRef:
                key: "BANIAS_TOPIC"
                name: "banias-frontend-config"
          - name: "BANIAS_PORT"
            valueFrom:
              configMapKeyRef:
                key: "BANIAS_PORT"
                name: "banias-frontend-config"
          - name: "BANIAS_METRICSPORT"
            valueFrom:
              configMapKeyRef:
                key: "BANIAS_METRICSPORT"
                name: "banias-frontend-config"
          - name: "BANIAS_PUBSUBMAXBATCH"
            valueFrom:
              configMapKeyRef:
                key: "BANIAS_PUBSUBMAXBATCH"
                name: "banias-frontend-config"
          - name: "BANIAS_PUBSUBAGGRIGATORS"
            valueFrom:
              configMapKeyRef:
                key: "BANIAS_PUBSUBAGGRIGATORS"
                name: "banias-frontend-config"
          - name: "BANIAS_PUBSUBMAXPUBLISHDELAY"
            valueFrom:
              configMapKeyRef:
                key: "BANIAS_PUBSUBMAXPUBLISHDELAY"
                name: "banias-frontend-config"
          - name: "BANIAS_MAXPUBSUBGOROUTINESAMOUNT"
            valueFrom:
              configMapKeyRef:
                key: "BANIAS_MAXPUBSUBGOROUTINESAMOUNT"
                name: "banias-frontend-config"
          - name: "BANIAS_MAXPUBSUBGOROUTINEIDLEDURATION"
            valueFrom:
              configMapKeyRef:
                key: "BANIAS_MAXPUBSUBGOROUTINEIDLEDURATION"
                name: "banias-frontend-config"
          - name: GOOGLE_APPLICATION_CREDENTIALS
            value: /var/secrets/google/key.json
          # TODO This setting makes nodes pull the docker image every time before
                  # starting the pod. This is useful when debugging, but should be turned
                  # off in production.
          imagePullPolicy: Always
        volumes:
          - name: google-cloud-key
            secret:
              secretName: pubsub-key
